name: Test Action
on:
  pull_request:
    branches: [ "main" ]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Multi version control
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute action
        id: bump_version
        uses: ./ 
        with:
          version_file_path: "./version.gradle"
          pr_labels: " dev  bump-patch "
          version_name_dev: "version_name_test_dev"
          version_code_dev: "version_code_test_dev"

      - name: Print current version & next version
        run: |
          echo ${{ steps.bump_version.outputs.current_version }}
          echo ${{ steps.bump_version.outputs.next_version }}